# Aliases and helpers
alias grep='grep --color'
alias mv='mv -i'
alias cp='cp -i'
alias lg='lazygit'
alias py='python'
alias h='history'
# alias vim='/opt/homebrew/bin/vim'
# alias vim='/usr/local/bin/vim'
alias vimzsh='vim $HOME/.zshrc'
alias sourcezsh='source $HOME/.zshrc'
alias nkfsjis='nkf -w --overwrite -s'
alias nkfutf='nkf -w --overwrite'
alias ls='ls -lGwFt'
alias la='ls -alht'
alias sed='gsed'

alias cdpee='cd /Users/minoriarahori/Documents/PyWork/MinoCatPeeDetection'
alias cdrepo='cd /Users/minoriarahori/Documents/PyWork'
